version: '3'
services:
    b2b:
        image: b2b
        container_name: b2b-blue
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=13001
        ports:
            - 13001:13001
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true