from typing import List, Dict, Any, Union, Optional
from datetime import date, datetime, time, timedelta

from app.schemas.schema import *


class B2BGoods(BaseModel): # b2b상품리스트
    uid: int = Field(0, title="T_B2B_GOODS 고유번호")
    contents: Optional[str] = Field(None, title='contents')
    benefit: Optional[str] = Field(None, title='benefit')
    attention: Optional[str] = Field(None, title='attention')
    option_list: Optional[List] = Field([], title='option_list')
    service_type: Optional[str] = Field("C", title='서비스 구분 C:고객사혜택, D:드림클럽')
    service_name: Optional[str] = Field(None, title='서비스명 T_B2B_GOODS_SERVICE')
    category: Optional[str] = Field(None, title='카테고리')
    seller_id: Optional[str] = Field(None, title='판매자아이디')
    seller_name: Optional[str] = Field(None, title='판매자명')
    title: Optional[str] = Field(None, title='상품명')
    sub_title: Optional[str] = Field(None, title='서브타이틀')
    keyword: Optional[str] = Field(None, title='키워드')
    thumb: Optional[str] = Field(None, title='메인 이미지')
    etc_images: Optional[List] = Field([], title='메인 이미지')
    option_title: Optional[str] = Field(None, title='옵션항목명')
    option_yn: Optional[str] = Field("Y", title='필수여부(Y/N)')
    option_value: Optional[str] = Field(None, title='옵션항목 콤마구분')
    option_type: Optional[str] = Field(None, title='옵션타입(A,B,C,D,E,F,G) T_B2B_GOODS_INFO')
    option_cnt: Optional[int] = Field(0, title='옵션갯수')
    market_price: Optional[int] = Field(0, title='정가')
    price: Optional[int] = Field(0, title='판매가')
    str_sale_percent: Optional[str] = Field(None, title='세일가')
    str_market_price: Optional[str] = Field(None, title='정가')
    str_price: Optional[str] = Field(None, title='판매가')
    commission_type: Optional[str] = Field("A", title='복지드림 수수료 타입(A,B)')
    commission: Optional[int] = Field(0, title='복지드림 수수료')
    other_service: Optional[str] = Field(None, title='추가상품')
    sort: Optional[int] = Field(0, title='순서')
    start_date: Optional[str] = Field(None, title='판매기간 시작일')
    end_date: Optional[str] = Field(None, title='판매기간 종료일')
    is_display: Optional[str] = Field("T", title='진열여부')
    state: Optional[str] = Field("200", title='상태')
    placeholder: Optional[str] = Field(None, title='[E] single, range / [F] images, allfile')
    memo: Optional[str] = Field(None, title='T_MEMO')
    create_at: Optional[datetime] = Field(None, title="등록일")
    update_at: Optional[datetime] = Field(None, title="수정일")
    delete_at: Optional[datetime] = Field(None, title="삭제일")
    mode: Optional[str] = Field(None, title="REG/MOD/DEL")
    class Config:
        orm_mode = True

class SellerInput(PPage_param):
    seller: Optional[str] = Field("")
    is_search: Optional[str] = Field("")
    class Config:
        orm_mode = True
        
class SellerDetail(BaseModel): # 업체
    uid: int = Field(0, title="T_B2B_SELLER 고유번호")
    seller_id: Optional[str] = Field(None, title='판매자아이디')
    seller_name: Optional[str] = Field(None, title='판매자명')
    account_cycle: Optional[str] = Field("1", title='정산 사이클')
    indend_md: Optional[str] = Field(None, title='상품담당자아이디')
    indend_md_name: Optional[str] = Field(None, title='상품담당자명')
    state: Optional[str] = Field("100", title='상태')
    ceo_name: Optional[str] = Field(None, title='대표자명')
    tel: Optional[str] = Field(None, title='대표번호')
    biz_no: Optional[str] = Field(None, title='사업자등록번호')
    biz_kind: Optional[str] = Field(None, title='업태')
    biz_item: Optional[str] = Field(None, title='종목')
    bank: Optional[str] = Field(None, title='정산 은행')
    account: Optional[str] = Field(None, title='정산 계좌번호')
    depositor: Optional[str] = Field(None, title='정산 계좌예금주')
    homepage: Optional[str] = Field(None, title='홈페이지')
    post: Optional[str] = Field(None, title='우편번호')
    addr: Optional[str] = Field(None, title='주소')
    addr_detail: Optional[str] = Field(None, title='주소상세')
    biz_file: Optional[str] = Field(None, title='사업자등록증')
    biz_hooper: Optional[str] = Field(None, title='통장사본')
    biz_file_fakename: Optional[str] = Field(None, title='사업자등록증 fakename')
    biz_hooper_fakename: Optional[str] = Field(None, title='통장사본 fakename')
    memo: Optional[str] = Field(None, title='T_MEMO')
    create_at: Optional[datetime] = Field(None, title="등록일")
    update_at: Optional[datetime] = Field(None, title="수정일")
    delete_at: Optional[datetime] = Field(None, title="삭제일")
    sort_array: Optional[List[int]] = Field([], title="변경할 메뉴 순서")
    mode: Optional[str] = Field(None, title="REG/MOD/DEL/SORT")
    class Config:
        orm_mode = True
        
class SellerStaff(BaseModel): # 담당자
    uid: int = Field(0, title="T_B2B_SELLER_STAFF 고유번호")
    seller_uid: int = Field(0, title="T_B2B_SELLER 고유번호")
    seller_id: Optional[str] = Field(None, title='판매자아이디')
    login_id: Optional[str] = Field(None, title='로그인 아이디')
    login_pw: Optional[str] = Field(None, title='로그인 비밀번호')
    name: Optional[str] = Field("", title='담당자명')
    roles: Optional[List[int]] = Field([], title="구분")
    depart: Optional[str] = Field(None, title='부서')
    position: Optional[str] = Field(None, title='직급/직책')
    tel: Optional[str] = Field(None, title='일반전화')
    mobile: Optional[str] = Field("", title='휴대전화')
    email: Optional[str] = Field("", title='이메일')
    sort: Optional[int] = Field(1, title='순서')
    alarm_email: Optional[str] = Field("T", title='이메일수신')
    alarm_kakao: Optional[str] = Field("T", title='알림톡수신')
    state: Optional[str] = Field(None, title='상태')
    mode: Optional[str] = Field(None, title="REG/MOD/DEL/COPY")
    class Config:
        orm_mode = True

class StaffInput(BaseModel):
    mode: Optional[str] = Field(None, title="REG/MOD/DEL/COPY")
    uid: Optional[int] = Field(0)
    seller_uid: Optional[str] = Field("")
    seller_id: Optional[str] = Field("")
    seller_name: Optional[str] = Field("")
    class Config:
        orm_mode = True
        
class B2BGoodsInput(BaseModel):
    uid: int = Field(0, title="T_B2B_GOODS.uid")
    service_type: Optional[str] = Field("C", title='서비스 구분 C:고객사혜택, D:드림클럽')
    category: Optional[str] = Field(None, title='카테고리')
    seller_id: Optional[str] = Field(None, title='판매자아이디')
    seller_name: Optional[str] = Field(None, title='판매자명')
    title: Optional[str] = Field(None, title='상품명')
    sub_title: Optional[str] = Field(None, title='서브타이틀')
    contents: Optional[str] = Field(None, title='상세내용')
    benefit: Optional[str] = Field(None, title='복지드림 멤버십 혜택')
    attention: Optional[str] = Field(None, title='유의사항')
    keyword: Optional[str] = Field(None, title='키워드')
    thumb: Optional[str] = Field(None, title='메인 이미지')
    option_yn: Optional[str] = Field("Y", title='옵션사용여부')
    option_value: Optional[str] = Field(None, title='옵션항목 콤마구분')
    option_cnt: Optional[int] = Field(0, title='옵션갯수')
    market_price: Optional[int] = Field(0, title='정가')
    price: Optional[int] = Field(0, title='판매가')
    str_sale_percent: Optional[str] = Field(None, title='세일가(문자열)')
    str_market_price: Optional[str] = Field(None, title='정가(문자열)')
    str_price: Optional[str] = Field(None, title='판매가(문자열)')
    commission_type: str = Field("A", title='카테고리')
    commission: Optional[int] = Field(0, title='복지드림 수수료')
    other_service: Optional[str] = Field(None, title='추가상품')
    sort: Optional[int] = Field(0, title='진열순서')
    start_date: Optional[str] = Field(None, title="판매기간 시작일")
    end_date: Optional[str] = Field(None, title="판매기간 종료일")
    is_display: Optional[str] = Field("T", title='진열여부')
    state: str = Field("200", title='상태')
    option_type: Optional[str] = Field(None, title='추가항목타입 A:한글입력폼, B:문장입력폼, C:드롭박스, D:라디오버튼, E:날짜, F:파일업로드, G:고객안내형 설정사항')
    option_title: Optional[str] = Field(None, title='항목명')
    placeholder: Optional[str] = Field(None, title='[E] single, range / [F] images, allfile')
    mode: Optional[str] = Field(None, title="REG/MOD/DEL/COPY")
    etc_images: Optional[List] = Field([], title='추가이미지')
    option_list: Optional[List] = Field([], title='option_list')
    seller_uid: Optional[int] = Field(0, title='판매자번호')
    goods_option_yn: Optional[str] = Field("", title='option_yn으로구분')
    memo: Optional[str] = Field("", title='메모')
    class Config:
        orm_mode = True