version: '3'
services:
    partner:
        image: partner
        container_name: partner-blue
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=10021
        ports:
            - 10021:10021
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true