version: '3'
services:
    partner:
        image: partner
        container_name: partner-green
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=10022
        ports:
            - 10022:10022
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true